
-- DAHA ÖNCE EKLEDİĞİNİZ TABLOLARI SİLER
DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

-- TABLOLARI EKLER
CREATE TABLE SHIPS(
	SHIPNO INT  primary key,
	SHIPNAME VARCHAR(20),
	SHIPTYPE VARCHAR(20),
	PNO INT CHECK (PNO>0),
	CAPTAIN_NO BIGINT
);

CREATE TABLE STAFF(
	SSN BIGINT primary key,		--9 haneli sosyal güvenlik no
    SUPERSSN BIGINT,               --gemide çalışanların superssn'i = kaptan, limanda çalışanların = başkan
    FNAME VARCHAR(20),
    LNAME VARCHAR(20),
    --KIND  VARCHAR(10),  			--worker, soldier, marine. 
    SEX	VARCHAR(7),	
    BDATE DATE, 	  							--doğum tarihi  
    SALARY INT,							-- 5000 TL, 10000 TL...
	P_NO INT,									--PORTS no
	S_NO INT  					--SHIP no		
);

CREATE TABLE PORTS(
	PORTS_NO INT  primary key,			-- army isimli PORTSların no'su 
    PORTS_NAME VARCHAR(20),	
    PORTS_TYPE VARCHAR(20),		--sadece 3 tür liman var: Commercial, Transfer and Army
    EXEC_NO BIGINT CHECK (EXEC_NO>0),     	--başkan ID'si
	PORTS_LOCATION VARCHAR(20)
);

CREATE TABLE EXECUTIVES(
	SSN BIGINT  primary key, 			--11 haneli T.C. kimlik no
	FNAME VARCHAR(20) NOT NULL,
	LNAME VARCHAR(20),
	PORTSNO INT NOT NULL,
	SALARY INT	
);


-- KISITLARI EKLER -- TABLOLARA İNSERT VE UPDATE İŞLEMLERİ YAPILDIKTAN SONRA EXECUTE EDİLMELİ
ALTER TABLE SHIPS ADD FOREIGN KEY(PNO) REFERENCES PORTS(PORTS_NO) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE SHIPS ADD FOREIGN KEY(CAPTAIN_NO) REFERENCES STAFF(SSN) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PORTS ADD FOREIGN KEY(EXEC_NO) REFERENCES EXECUTIVES(SSN) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE STAFF ADD FOREIGN KEY(P_NO) REFERENCES PORTS(PORTS_NO) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE STAFF ADD FOREIGN KEY(SUPERSSN) REFERENCES STAFF(SSN) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE STAFF ADD FOREIGN KEY(S_NO) REFERENCES SHIPS(SHIPNO) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EXECUTIVES ADD FOREIGN KEY(PORTSNO) REFERENCES PORTS(PORTS_NO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PORTS ADD CHECK(EXEC_NO>0);
ALTER TABLE PORTS ADD CHECK(PORTSNO>0);





























